# Generated by Django 4.0.4 on 2022-05-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='<django.db.models.fields.CharField>'),
        ),
    ]
